---
# magento_add_admin_user.yml
# This play book create a list of admin users on Magento Admin
# run :
#   ansible-playbook magento_add_admin_user.yml --extra-vars "target=name_of_instance"

- name: add magento admin users on selected environment.
  hosts: '{{ target }}'
  gather_facts: yes
  vars_files:
    - ./group_vars/user_vars.yml

  roles:
    - magento_add_admin